---

version: "3.8"
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    container_name: node-exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
  mtr-agent:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mtr-agent
    restart: unless-stopped
    environment:
      PROJECT_UUID: [your_project_uuid]
      SENSOR_NAME: Node Agent
      PROMETHEUS_HOST: http://node-exporter:9100/metrics
